### PR TITLE
Ignore the current venv

### PR DESCRIPTION
**Pull request by almet**
r? @phrawzty @leplatrem

### CODE REVIEW

**Comment by phrawzty** [comment]
lgtm; however, will this negatively affect established behaviour expectations?

**Comment by almet** [comment]
Nope, only us are currently using it, and it's broken if you use your own venv (it seems). I even think I need to fix this in pelican upstream.

**Comment by Natim** [comment]
:( I wouldn't have fixed it that way anyway.

**Comment by leplatrem** [comment]
Not too late @Natim! Do not hesitate to open a PR with revert and your fix!

**Comment by Natim** [comment]
Ok thanks.

**Pull request merged**
