### PR TITLE
Remove the last article for now

### PR DESCRIPTION
**Pull request by almet**
r? @leplatrem

### CODE REVIEW

**Comment by Natim** [comment]
If you want but why not upgrading it while changing the date?

**Comment by almet** [comment]
Goal here is to remove it from the website, until it's finished.

**Comment by Natim** [comment]
Yes I don't understand what would be the benefit of doing that.

**Comment by almet** [comment]
Because it's not finished!

**Comment by Natim** [comment]
Yes but nothing is never totally finished, we can still improve the article even if we don't un-publish it. I don't think people reading this first version (un-finished one) will get harmed, they will get some information that may help them even if we can still improve this information.

That's just my 2 cents, if you think it is important to un-publish it until it gets better please do :)

**Comment by almet** [comment]
That's two different ways to think. I prefer to actually only publish great content, and not go too quickly :)

**Comment by Natim** [comment]
Sure no worries :)

**Pull request merged**
