### PR TITLE
Use better fonts for the theme

### PR DESCRIPTION
**Pull request by almet**
I feel we deserve better fonts than what we have currently. This is a first try, if you have other fonts to propose, please do.

fonts

to compare to:

fonts-before

### CODE REVIEW

**Comment by Natim** [comment]
LGTM/

**Comment by leplatrem** [comment]
Great!
(_plus, I read recently that some fonts give more credits than others.._ :D)

Personnally, I find it slightly too small to read...

**Comment by Natim** [comment]
Yes +1 on the size :)

**Comment by leplatrem** [comment]
It looks like not every block was impacted:

capture d ecran de 2015-05-28 09 33 32

```
.content {
  font-family: "aleo";
}

@media (min-width: 100em) { /* less than 100 ? */
  .content {
    font-size: 1.2em;
  }
}
```

**Comment by almet** [comment]
Yes, I only used it on paragraphs. I can use it as the default font by putting it in "body".

About the font size, we can of course increase it a bit more. I'll update the PR.

**Comment by almet** [comment]
Updated.

better-fonts-again

**Comment by leplatrem** [comment]
r+ :) nice

**Pull request merged**
