### PR TITLE
Venv management

### PR DESCRIPTION
**Pull request by Natim**
Fix #33 differently

### CODE REVIEW

**Comment by leplatrem** [comment]
It does not work if the venv is not activated:

```
$ deactivate
$ make serve
cd /home/mathieu/Documents/Websites/servicedenuages.fr/output && .venv/bin/python -m pelican.server
/bin/sh: 1: .venv/bin/python: not found
Makefile:44: recipe for target 'serve' failed
make: *** [serve] Error 127

```

**Comment by Natim** [comment]
True thank you for noticing. Updated.

**Comment by leplatrem** [comment]
Works !

r+

**Pull request merged**
