### PR TITLE
Update code with @bnjbvr remarks.

### PR DESCRIPTION
**Pull request by Natim**
r? @michielbdejong

### CODE REVIEW

**Comment by michielbdejong** [comment]
r+, great! I was actually just thinking the same thing, it _is_ better this way. And we can copy the same changes over to the French translation.

**Comment by Natim** [comment]
The french translation already have them. Thanks.

**Comment by Natim** [comment]
Now I have SyntaxError: missing ; before statement 4:6

Which is:

```
const rawStringToByteArray = (str) => {
  const strLen = str.length;
  let byteArray = new Uint8Array(strLen);  <===
  for (let i = 0; i < strLen; i++) {
    byteArray[i] = str.charCodeAt(i);
  }
```

**Comment by michielbdejong** [comment]
Me too, puzzling! The same code works if I take this page:

``` html
<!DOCTYPE html>
<html>
  <body>
  </body>
  <script src="scripts/kinto-61ad959.min.js"></script>
</html>
```

and paste https://raw.githubusercontent.com/mozilla-services/servicedenuages.fr/master/content/scripts/kinto-encryption-example.js into the console...

Not sure if this is a bug in Firefox? Let's revert to `var`, so that it works? (unless you can figure out what's going on here)...

**Comment by n1k0** [comment]
Note that the code raises a slightly different yet possibly related error, also preventing the code to run properly:

> Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
> kinto-chiffrer-ses-donnees:320 GET http://piwik.notmyidea.org/piwik.js net::ERR_BLOCKED_BY_CLIENT(anonymous function) @ kinto-chiffrer-ses-donnees:320(anonymous function) @ kinto-chiffrer-ses-donnees:321

I don't have the time to investigate just now, but maybe wrapping the offending code within some strictly scoped IIFE would solve the issue.

**Pull request merged**
